# Generated by Django 6.0.9 on 2026-10-06 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField(help_text='Earlier than start means the shift runs past midnight.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['department', 'start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable id used by the frontend, e.g. 'icu'.", max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(help_text='What kind of care the ward gives.', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. ICU-01. Also the bed's API id.", max_length=20, unique=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('free', 'Free'), ('outOfService', 'Out of service')], default='free', max_length=20)),
                ('status_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_initials', models.CharField(blank=True, max_length=10)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_discharge', models.DateField(blank=True, null=True)),
                ('isolation', models.CharField(blank=True, choices=[('contact', 'Contact precautions'), ('droplet', 'Droplet precautions'), ('airborne', 'Airborne precautions')], max_length=10)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospitals.ward')),
            ],
            options={
                'ordering': ['ward__sort_order', 'label'],
                'indexes': [models.Index(fields=['status'], name='hospitals_b_status_45b872_idx')],
            },
        ),
    ]
