# Generated by Django 6.0.9 on 2026-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(help_text='ISBT 128 donation identification number. Also the API id.', max_length=30, unique=True)),
                ('group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('component', models.CharField(choices=[('redCells', 'Red cells'), ('plasma', 'Plasma'), ('platelets', 'Platelets'), ('cryo', 'Cryo')], max_length=12)),
                ('collected_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('quarantined', 'Quarantined'), ('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('expired', 'Expired')], default='quarantined', max_length=12)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['group', 'component', 'status'], name='blood_blood_group_ed8f3b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('collected_at'))), name='blood_unit_expires_after_collection')],
            },
        ),
    ]
