"""Single source of truth for the initial product backlog.

`sync_github.py` turns this into GitHub labels, milestones and issues, and `render_backlog_doc.py`
renders docs/product/backlog.md from it. After the initial import, GitHub is the live backlog;
edit issues there, not here.

Derived from the WBS (Muzammil Siddiqui, K232001) and the CityCare proposal. Points are initial
estimates on a Fibonacci scale; the team re-estimates during Friday sprint planning.
"""

from datetime import date, timedelta

SPRINT_1_START = date(2026, 10, 3)  # Saturday; sprints run Sat → Fri, ceremonies Fri 22:00 PKT

SPRINT_GOALS = [
    "Discovery & foundation: repo/CI live, ERD, wireframes, login works end to end",
    "Access & hospital network: RBAC, hospitals registered, audit logging, shared resource model",
    "Blood inventory & donors: units tracked from collection through testing to expiry",
    "Hospital resources: beds, equipment and operating rooms registered and bookable",
    "Emergency requests: cases created, requirements captured, lifecycle tracked",
    "Matching engine: compatible candidates found, scored and explained",
    "Reservation & transfers: atomic reservations, allocation records, inter-hospital transfers",
    "Ambulances, notifications, dashboards & audit search",
    "Hardening & final demo: end-to-end MVP scenario, deployment, final report",
]


def sprint_dates(n):
    start = SPRINT_1_START + timedelta(weeks=n - 1)
    return start, start + timedelta(days=6)


EPICS = {
    "E0": ("Project Setup & Process", "6e7781"),
    "E1": ("User & Hospital Management", "1f6feb"),
    "E2": ("Resource Management", "8250df"),
    "E3": ("Blood Management", "cf222e"),
    "E4": ("Emergency Request Management", "bc4c00"),
    "E5": ("Matching & Allocation Engine", "1a7f37"),
    "E6": ("Transfers & Logistics", "0969da"),
    "E7": ("Dashboards, Notifications & Reports", "9a6700"),
    "E8": ("Security & Audit", "57606a"),
}

# sprint=None → not scheduled yet (secondary / stretch scope, pulled in only if velocity allows)
# type: story | task       priority: highest | high | medium | low
BACKLOG = [
    # ── Sprint 1 ─────────────────────────────────────────────────────────────
    dict(type="task", epic="E0", sprint=1, points=3, priority="highest", area=["devops"], wbs="-",
         title="Repository, CI pipeline and Docker dev environment",
         story="Set up the monorepo (Django + React), GitHub Actions CI, Docker Compose and contribution rules.",
         ac=["CI runs lint, migrations check and tests for backend and frontend on every PR",
             "`docker compose up` starts Postgres, API and frontend",
             "README and CONTRIBUTING explain setup and workflow"]),
    dict(type="task", epic="E0", sprint=1, points=1, priority="highest", area=["devops"], wbs="-",
         title="Team onboarding: everyone runs the project locally",
         story="Every member clones the repo, runs it locally and opens a first PR adding themselves to docs/scrum/team.md.",
         ac=["All 8 members have merged a PR to team.md", "Everyone has joined the GitHub Project and Discord channels"]),
    dict(type="task", epic="E0", sprint=1, points=5, priority="highest", area=["backend", "docs"], wbs="-",
         title="Domain model and ERD for the MVP",
         story="Design the relational schema covering users, hospitals, resources, blood, requests, reservations, transfers, notifications and audit.",
         ac=["ERD committed to docs/architecture/ (image + source)",
             "Shared Resource abstraction defined so beds/equipment/OR/blood fit one model",
             "State machines documented for blood unit, request, reservation and transfer",
             "Reviewed by at least 3 team members"]),
    dict(type="task", epic="E0", sprint=1, points=5, priority="high", area=["frontend", "docs"], wbs="-",
         title="UI wireframes for core user journeys",
         story="Low-fidelity wireframes for login, hospital dashboard, inventory, emergency request, matching results and transfer tracking.",
         ac=["Wireframes linked from docs/architecture/README.md", "Navigation map covers every MVP role"]),
    dict(type="task", epic="E0", sprint=1, points=3, priority="high", area=["frontend"], wbs="-",
         title="Frontend app shell: layout, routing, design tokens, API client",
         story="Base layout with sidebar navigation, route structure per module, shared components and an authenticated API client.",
         ac=["Layout renders on desktop and mobile widths", "Route placeholders exist for every MVP module",
             "API client sends session cookies and CSRF token"]),
    dict(type="task", epic="E0", sprint=1, points=2, priority="high", area=["docs"], wbs="3.3",
         title="Document blood compatibility rules from an authoritative source",
         story="Write the ABO/Rh compatibility tables per component (RBC, plasma, platelets) with citations, to be used as configurable rules.",
         ac=["docs/domain/blood-compatibility.md lists rules per component with sources",
             "Scope note: the system is a coordination aid, not a clinical decision-maker"]),
    dict(type="story", epic="E1", sprint=1, points=3, priority="highest", area=["backend", "frontend"], wbs="1.1 User Accounts",
         title="User accounts",
         story="As a system administrator, I want to create and deactivate staff accounts so that only authorised people can use the platform.",
         ac=["Admin can create a user with name, email, hospital and role",
             "Deactivated users cannot log in",
             "Passwords are hashed and validated against Django's password validators"]),
    dict(type="story", epic="E1", sprint=1, points=5, priority="highest", area=["backend", "frontend"], wbs="1.1 Login & Session Security",
         title="Login, logout and session security",
         story="As a hospital staff member, I want to log in securely so that I can access my hospital's functions.",
         ac=["Given valid credentials, when I log in, then I reach my dashboard",
             "Given invalid credentials, then I see a generic error and no account details leak",
             "Sessions expire after inactivity; logout invalidates the session",
             "Repeated failed logins are rate-limited"]),

    # ── Sprint 2 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E1", sprint=2, points=3, priority="highest", area=["backend"], wbs="1.2 Role Management",
         title="Role management",
         story="As a system administrator, I want to assign roles (admin, hospital staff, blood-bank staff, emergency coordinator, management) so that permissions match responsibilities.",
         ac=["Roles are seeded by a migration", "Admin can change a user's role", "Role change is audit-logged"]),
    dict(type="story", epic="E1", sprint=2, points=5, priority="highest", area=["backend", "frontend"], wbs="1.2 Access Control",
         title="Role-based access control on API and UI",
         story="As a user, I want to only see and do what my role permits so that sensitive actions are protected.",
         ac=["Every API endpoint declares a permission class; unauthorised calls return 403",
             "Staff can only modify resources belonging to their own hospital",
             "Frontend hides navigation and actions the user cannot perform",
             "Permission tests cover each role"]),
    dict(type="story", epic="E1", sprint=2, points=5, priority="highest", area=["backend", "frontend"], wbs="1.3 Hospital Registration",
         title="Hospital registration",
         story="As an administrator, I want to register hospitals and blood banks with their location so that they can join the network.",
         ac=["Admin can create, edit and deactivate a hospital with name, type, address and coordinates",
             "Hospital list is searchable and filterable by type", "Deactivated hospitals are excluded from matching"]),
    dict(type="story", epic="E1", sprint=2, points=3, priority="high", area=["backend", "frontend"], wbs="1.3 Hospital Structure",
         title="Hospital structure: departments, wards and storage locations",
         story="As a hospital administrator, I want to define departments, wards and storage locations so that resources can be placed precisely.",
         ac=["Departments/wards/locations belong to exactly one hospital", "Locations can be referenced by resources"]),
    dict(type="story", epic="E1", sprint=2, points=3, priority="medium", area=["backend", "frontend"], wbs="1.3 Hospital Capability Profile",
         title="Hospital capability profile",
         story="As a coordinator, I want to see each hospital's capabilities (e.g. trauma centre, NICU, blood bank) so that I can route emergencies sensibly.",
         ac=["Capabilities are a managed list; hospitals can have many", "Capability shown on hospital detail page"]),
    dict(type="task", epic="E2", sprint=2, points=5, priority="highest", area=["backend"], wbs="2.0",
         title="Shared resource model and status state machine",
         story="Implement the abstract Resource model and lifecycle state machine that blood units, beds, equipment and operating rooms build on.",
         ac=["Invalid status transitions raise a domain error and are unit-tested",
             "Every status change records who/when/why", "Design documented in docs/architecture"]),
    dict(type="story", epic="E8", sprint=2, points=5, priority="high", area=["backend"], wbs="8.1 Action Logging",
         title="Audit logging of critical actions",
         story="As an administrator, I want critical actions recorded so that every change to resources, requests and permissions is traceable.",
         ac=["Audit entry stores actor, action, target, before/after values, timestamp",
             "Audit records cannot be edited or deleted through the API",
             "Reusable helper/mixin so other modules log with one call"]),
    dict(type="task", epic="E0", sprint=2, points=3, priority="high", area=["backend"], wbs="-",
         title="Synthetic seed data command",
         story="A `manage.py seed_demo` command that creates 3+ hospitals and a user per role with synthetic data.",
         ac=["Command is idempotent", "No real patient or donor data is used", "Seed credentials documented in README"]),

    # ── Sprint 3 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E3", sprint=3, points=5, priority="highest", area=["backend", "frontend"], wbs="3.2 Blood Unit Registration",
         title="Blood unit registration",
         story="As blood-bank staff, I want to register individual blood units so that inventory is tracked at unit level.",
         ac=["Unit has unique ID, blood group, component, collection date, expiry date and storage location",
             "Expiry date defaults from component shelf life and cannot precede collection date",
             "Duplicate unit IDs are rejected"]),
    dict(type="story", epic="E3", sprint=3, points=5, priority="highest", area=["backend", "frontend"], wbs="3.2 Blood Collection and Testing",
         title="Blood collection and testing status",
         story="As blood-bank staff, I want to record screening results so that only approved units become available for allocation.",
         ac=["Units start as 'quarantined' until all tests pass",
             "A failed test moves the unit to 'discarded' with a reason",
             "Only 'available' units appear in searches"]),
    dict(type="story", epic="E3", sprint=3, points=5, priority="high", area=["backend", "frontend"], wbs="3.2 Expiry and Stock Control",
         title="Expiry alerts and stock levels",
         story="As blood-bank staff, I want near-expiry and low-stock alerts so that units are used before expiring and shortages are spotted early.",
         ac=["Units past expiry are automatically marked expired",
             "Near-expiry threshold (default 3 days) is configurable",
             "Stock view shows counts per blood group and component with low-stock highlighting"]),
    dict(type="story", epic="E3", sprint=3, points=3, priority="high", area=["backend", "frontend"], wbs="3.1 Donor Registration",
         title="Donor registration",
         story="As blood-bank staff, I want to register donors so that collected units can be traced to a donor record.",
         ac=["Donor record stores synthetic identity, blood group and contact", "Blood units can be linked to a donor"]),
    dict(type="story", epic="E3", sprint=3, points=3, priority="medium", area=["backend", "frontend"], wbs="3.1 Donor Eligibility Screening",
         title="Donor eligibility screening",
         story="As blood-bank staff, I want to record eligibility screening so that ineligible donors are not scheduled.",
         ac=["Minimum interval between donations enforced", "Ineligible donors flagged with reason"]),
    dict(type="story", epic="E3", sprint=3, points=3, priority="low", area=["backend", "frontend"], wbs="3.1 Donation Appointments",
         title="Donation appointments",
         story="As blood-bank staff, I want to schedule donation appointments so that donor intake is planned.",
         ac=["Appointments cannot be double-booked for the same slot", "Only eligible donors can be booked"]),

    # ── Sprint 4 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E2", sprint=4, points=3, priority="high", area=["backend", "frontend"], wbs="2.1 Bed Registry",
         title="Bed registry",
         story="As hospital staff, I want to register beds by type and ward so that bed capacity is known.",
         ac=["Bed types include ICU, emergency, general, isolation, NICU", "Each bed belongs to a ward"]),
    dict(type="story", epic="E2", sprint=4, points=5, priority="high", area=["backend", "frontend"], wbs="2.1 Bed Availability",
         title="Real-time bed availability",
         story="As hospital staff, I want to update bed status so that the network sees current availability.",
         ac=["Statuses: available, occupied, cleaning, out of service, reserved",
             "Status change is one click from the ward view", "Changes are audit-logged"]),
    dict(type="story", epic="E2", sprint=4, points=3, priority="medium", area=["backend", "frontend"], wbs="2.1 Capacity Monitoring",
         title="Bed capacity monitoring",
         story="As management, I want occupancy per ward and bed type so that capacity pressure is visible.",
         ac=["Occupancy % per ward and bed type", "Wards above a configurable threshold are highlighted"]),
    dict(type="story", epic="E2", sprint=4, points=3, priority="high", area=["backend", "frontend"], wbs="2.2 Equipment Registry",
         title="Equipment registry",
         story="As hospital staff, I want to register critical equipment (ventilators, monitors, defibrillators, dialysis) so that it can be located and shared.",
         ac=["Equipment has type, identifier, location and status", "Filterable by type and status"]),
    dict(type="story", epic="E2", sprint=4, points=3, priority="medium", area=["backend", "frontend"], wbs="2.2 Equipment Status",
         title="Equipment operational status",
         story="As hospital staff, I want to track equipment status so that only working equipment is offered.",
         ac=["Statuses: available, in use, maintenance, out of service", "Equipment in maintenance is excluded from matching"]),
    dict(type="story", epic="E2", sprint=4, points=3, priority="medium", area=["backend", "frontend"], wbs="2.3 Operating Room Registry",
         title="Operating room registry",
         story="As hospital staff, I want to register operating rooms with their capabilities so that suitable rooms can be found.",
         ac=["OR has name, capabilities (e.g. cardiac, trauma) and status"]),
    dict(type="story", epic="E2", sprint=4, points=5, priority="medium", area=["backend", "frontend"], wbs="2.3 Operating Room Scheduling",
         title="Operating room scheduling",
         story="As hospital staff, I want to book OR time slots so that scheduling conflicts are avoided.",
         ac=["Overlapping bookings for the same room are rejected (DB constraint + test)",
             "Day view shows bookings per room"]),

    # ── Sprint 5 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E4", sprint=5, points=5, priority="highest", area=["backend", "frontend"], wbs="4.1 Create Emergency Case",
         title="Create emergency case",
         story="As an emergency coordinator, I want to log an emergency case so that resource fulfilment can begin immediately.",
         ac=["Case created in ≤ 3 form steps", "Case gets a unique reference and 'open' status",
             "No patient-identifying data is required"]),
    dict(type="story", epic="E4", sprint=5, points=3, priority="high", area=["backend", "frontend"], wbs="4.1 Severity and Priority",
         title="Emergency severity and priority",
         story="As an emergency coordinator, I want to classify severity so that critical cases are handled first.",
         ac=["Severity levels: critical, high, moderate, low", "Lists sort by severity then age", "Critical cases are visually distinct"]),
    dict(type="story", epic="E4", sprint=5, points=5, priority="highest", area=["backend", "frontend"], wbs="4.2 Define Requirements",
         title="Define resource requirements for a case",
         story="As an emergency coordinator, I want to specify what a case needs (blood, bed, equipment, OR) so that the system can search for it.",
         ac=["A case can have multiple requirement items of different resource types",
             "Blood items capture group, component and quantity"]),
    dict(type="story", epic="E4", sprint=5, points=5, priority="high", area=["backend", "frontend"], wbs="4.2 Availability Check",
         title="Local availability check",
         story="As an emergency coordinator, I want to see what my own hospital already has so that I only request externally what is missing.",
         ac=["Each requirement shows locally available quantity",
             "Shortfall is computed and carried into the matching step"]),
    dict(type="story", epic="E4", sprint=5, points=5, priority="highest", area=["backend", "frontend"], wbs="4.3 Request Status Tracking",
         title="Emergency request status tracking",
         story="As hospital staff, I want to track a request's status so that I know whether it is being fulfilled.",
         ac=["Statuses: open, matching, partially fulfilled, fulfilled, escalated, closed, cancelled",
             "Status history timeline shown on request page", "Invalid transitions rejected"]),
    dict(type="story", epic="E4", sprint=5, points=3, priority="medium", area=["backend", "frontend"], wbs="4.3 Escalation and Closure",
         title="Request escalation and closure",
         story="As an emergency coordinator, I want unfulfilled critical requests escalated and fulfilled ones closed so that nothing is forgotten.",
         ac=["Critical requests unfulfilled after a configurable time are escalated",
             "Closing a request requires an outcome note"]),
    dict(type="story", epic="E3", sprint=5, points=5, priority="highest", area=["backend", "frontend"], wbs="3.3 Blood Request",
         title="Emergency blood request",
         story="As hospital staff, I want to submit a blood request with group, component, quantity and urgency so that fulfilment can start.",
         ac=["Request validated (quantity > 0, supported component)", "Request appears in the network request feed"]),

    # ── Sprint 6 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E3", sprint=6, points=8, priority="highest", area=["backend"], wbs="3.3 Compatibility Matching",
         title="Blood compatibility matching engine",
         story="As a hospital, I want the system to find compatible, approved, unexpired, unreserved units across the network so that blood is located quickly.",
         ac=["Compatibility rules loaded from configuration (documented table)",
             "Excludes untested, expired, reserved and discarded units",
             "Unit tests cover every ABO/Rh combination per component"]),
    dict(type="story", epic="E5", sprint=6, points=5, priority="highest", area=["backend"], wbs="5.1 Find Candidate Hospitals",
         title="Find candidate hospitals",
         story="As an emergency coordinator, I want hospitals that can supply a needed resource listed so that I can request from them.",
         ac=["Works for blood, beds, equipment and OR via the shared resource model",
             "Search over seeded data returns in < 1 s"]),
    dict(type="story", epic="E5", sprint=6, points=3, priority="medium", area=["backend", "frontend"], wbs="5.1 Distance and Travel Time",
         title="Distance and estimated travel time",
         story="As an emergency coordinator, I want distance and approximate travel time shown so that nearer sources are preferred.",
         ac=["Straight-line distance from coordinates (Haversine)", "Travel time estimated from average city speed (simulated)"]),
    dict(type="story", epic="E5", sprint=6, points=5, priority="high", area=["backend"], wbs="5.2 Scoring Model",
         title="Configurable scoring model",
         story="As a coordinator, I want candidates scored by configurable rules (distance, expiry, quantity) so that selection is consistent.",
         ac=["Scoring implemented as interchangeable strategy classes",
             "Earliest-expiry-first is the default blood strategy", "Weights configurable without code changes"]),
    dict(type="story", epic="E5", sprint=6, points=3, priority="high", area=["backend", "frontend"], wbs="5.2 Ranking and Explanation",
         title="Ranked results with explanation",
         story="As a coordinator, I want to see why a candidate is ranked first so that I can trust the recommendation.",
         ac=["Each result shows its score breakdown", "Results UI sorted by score with clear top recommendation"]),
    dict(type="story", epic="E5", sprint=6, points=8, priority="medium", area=["backend"], wbs="5.2 Multi-Resource Matching",
         title="Multi-resource matching",
         story="As a coordinator, I want hospitals that satisfy several requirements at once (e.g. ICU bed + ventilator + blood) ranked higher so that patients go where everything is available.",
         ac=["Hospitals meeting all requirements rank above partial matches",
             "Partial matches show which requirements are unmet"]),

    # ── Sprint 7 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E5", sprint=7, points=8, priority="highest", area=["backend"], wbs="5.3 Resource Reservation",
         title="Atomic resource reservation",
         story="As staff, I want matched resources reserved atomically so that two requests cannot claim the same unit.",
         ac=["Reservation uses a DB transaction with row locking (select_for_update)",
             "Reservations expire after a configurable hold time and release resources",
             "Reserved resources disappear from other searches"]),
    dict(type="story", epic="E5", sprint=7, points=5, priority="highest", area=["backend"], wbs="5.3 Conflict Prevention",
         title="Concurrency conflict prevention tests",
         story="As the team, we want proven protection against double allocation so that data integrity holds under load.",
         ac=["Automated test fires concurrent reservations for the same unit; exactly one succeeds",
             "Negative inventory is impossible (DB constraint)"]),
    dict(type="story", epic="E5", sprint=7, points=3, priority="high", area=["backend", "frontend"], wbs="5.3 Allocation Record",
         title="Allocation record",
         story="As staff, I want confirmed reservations turned into allocation records so that there is a permanent history of who received what.",
         ac=["Allocation links request, resource, hospital and staff member", "Visible in request history"]),
    dict(type="story", epic="E3", sprint=7, points=5, priority="high", area=["backend", "frontend"], wbs="3.3 Blood Allocation",
         title="Blood allocation workflow",
         story="As blood-bank staff, I want to confirm allocation of reserved units so that inventory and request states update together.",
         ac=["Allocating updates unit status and request fulfilment in one transaction",
             "Partially fulfilled requests show remaining quantity"]),
    dict(type="story", epic="E6", sprint=7, points=5, priority="highest", area=["backend", "frontend"], wbs="6.1 Transfer Request",
         title="Inter-hospital transfer request",
         story="As a requesting hospital, I want to request resources from another hospital, and as the supplying hospital approve or reject it, so that shortages are covered while suppliers keep control.",
         ac=["Supplier can approve or reject with reason", "Approval reserves the units; rejection releases them"]),
    dict(type="story", epic="E6", sprint=7, points=5, priority="high", area=["backend", "frontend"], wbs="6.1 Transfer Tracking",
         title="Transfer tracking",
         story="As both hospitals, I want to see transfer status so that everyone knows where the resource is.",
         ac=["States: requested, approved, dispatched, in transit, delivered, rejected, cancelled",
             "Status history with timestamps"]),
    dict(type="story", epic="E6", sprint=7, points=3, priority="high", area=["backend", "frontend"], wbs="6.1 Delivery Confirmation",
         title="Delivery confirmation",
         story="As the requesting hospital, I want to confirm receipt so that inventory moves to my hospital and the request updates.",
         ac=["Receipt moves units to receiver inventory in one transaction", "Request fulfilment recalculated"]),

    # ── Sprint 8 ─────────────────────────────────────────────────────────────
    dict(type="story", epic="E6", sprint=8, points=3, priority="medium", area=["backend", "frontend"], wbs="6.2 Ambulance Registry",
         title="Ambulance registry",
         story="As a coordinator, I want ambulances registered with their base hospital and type so that transport capacity is known.",
         ac=["Ambulance has identifier, type, base hospital and status"]),
    dict(type="story", epic="E6", sprint=8, points=5, priority="medium", area=["backend", "frontend"], wbs="6.2 Dispatch and Trip Tracking",
         title="Ambulance dispatch and trip tracking",
         story="As a coordinator, I want to dispatch an ambulance for a transfer and track the trip so that delivery is coordinated.",
         ac=["Only available ambulances can be dispatched", "Trip states: dispatched, en route, arrived, completed (simulated)"]),
    dict(type="story", epic="E7", sprint=8, points=5, priority="high", area=["backend"], wbs="7.1 Notification Service",
         title="Notification service",
         story="As staff, I want to be notified of requests, approvals and status changes relevant to my hospital so that I can act quickly.",
         ac=["In-app notifications with read/unread state",
             "Channel abstraction so email/SMS can be added later", "Notifications created from domain events"]),
    dict(type="story", epic="E7", sprint=8, points=3, priority="medium", area=["frontend"], wbs="7.1 Alerts",
         title="In-app alerts UI",
         story="As staff, I want a notification bell and alert banners for critical events so that urgent items are not missed.",
         ac=["Unread count badge", "Critical alerts shown as a banner until acknowledged"]),
    dict(type="story", epic="E7", sprint=8, points=5, priority="high", area=["frontend", "backend"], wbs="7.2 Hospital Dashboard",
         title="Hospital dashboard",
         story="As hospital staff, I want a dashboard of my inventory, beds, active requests and transfers so that I see my situation at a glance.",
         ac=["Shows stock by blood group, bed occupancy, open requests, pending transfers", "Refreshes without page reload"]),
    dict(type="story", epic="E7", sprint=8, points=5, priority="high", area=["frontend", "backend"], wbs="7.2 City Command Centre",
         title="City command centre dashboard",
         story="As management, I want a city-wide view of availability, shortages and active emergencies so that I can monitor conditions.",
         ac=["Aggregates across all hospitals", "Highlights shortages and near-expiry units network-wide"]),
    dict(type="story", epic="E8", sprint=8, points=3, priority="medium", area=["backend", "frontend"], wbs="8.1 Audit Search & Export",
         title="Audit search and export",
         story="As an administrator, I want to search and export the audit trail so that actions can be reviewed.",
         ac=["Filter by actor, action type, entity and date range", "Export to CSV"]),

    # ── Sprint 9 ─────────────────────────────────────────────────────────────
    dict(type="task", epic="E0", sprint=9, points=5, priority="highest", area=["qa"], wbs="-",
         title="End-to-end MVP scenario test",
         story="Automate the MVP acceptance scenario: request → match → reserve → transfer → receipt across 3 seeded hospitals.",
         ac=["Scenario runs in CI", "Covers every MVP acceptance criterion in the proposal (§23)"]),
    dict(type="task", epic="E0", sprint=9, points=3, priority="high", area=["qa", "backend"], wbs="-",
         title="Security and performance hardening",
         story="Review permissions, run Django deployment checks, and load-test the search on a synthetic city-sized dataset.",
         ac=["`manage.py check --deploy` clean on staging", "Search p95 latency recorded in the final report"]),
    dict(type="task", epic="E0", sprint=9, points=3, priority="highest", area=["devops"], wbs="-",
         title="Final staging deployment and demo data",
         story="Stable staging environment seeded with the demo scenario.",
         ac=["Staging URL in README", "Demo script rehearsed end to end"]),
    dict(type="task", epic="E0", sprint=9, points=3, priority="highest", area=["docs"], wbs="-",
         title="Final report and demo presentation",
         story="Compile the final project report (process + product), velocity/burndown history and demo slides.",
         ac=["All sprint reviews/retros linked", "Velocity and burndown charts included"]),

    # ── Secondary / stretch (unscheduled) ────────────────────────────────────
    dict(type="story", epic="E2", sprint=None, points=3, priority="low", area=["backend", "frontend"], wbs="2.4 Doctor Profiles",
         title="Specialist doctor profiles",
         story="As a coordinator, I want specialist profiles per hospital so that I know which expertise exists where.",
         ac=["Profile has specialty and hospital"]),
    dict(type="story", epic="E2", sprint=None, points=3, priority="low", area=["backend", "frontend"], wbs="2.4 On-Call and Availability",
         title="Specialist on-call availability",
         story="As a coordinator, I want to see which specialists are on call now so that emergencies reach the right expert.",
         ac=["On-call schedule per specialist", "'Available now' filter"]),
    dict(type="story", epic="E6", sprint=None, points=3, priority="low", area=["backend", "frontend"], wbs="6.3 Transfer Need Check",
         title="Patient transfer need check",
         story="As a coordinator, I want the system to flag when a case's requirements can't be met locally so that a patient transfer is considered.",
         ac=["Flag raised when local availability check fails for critical requirements"]),
    dict(type="story", epic="E6", sprint=None, points=5, priority="low", area=["backend", "frontend"], wbs="6.3 Destination Selection",
         title="Patient transfer destination selection",
         story="As a coordinator, I want a recommended destination hospital so that the patient goes where all needs are met.",
         ac=["Uses multi-resource matching to recommend a destination"]),
    dict(type="story", epic="E6", sprint=None, points=3, priority="low", area=["backend", "frontend"], wbs="6.3 Transfer Completion",
         title="Patient transfer completion",
         story="As the receiving hospital, I want to confirm patient arrival so that the case moves to my hospital.",
         ac=["Arrival confirmation updates case ownership"]),
    dict(type="story", epic="E7", sprint=None, points=3, priority="low", area=["backend", "frontend"], wbs="7.3 Operational Reports",
         title="Operational reports",
         story="As management, I want historical reports (requests, fulfilment time, wastage) so that I can plan.",
         ac=["Reports for a selectable date range"]),
    dict(type="story", epic="E7", sprint=None, points=2, priority="low", area=["backend", "frontend"], wbs="7.3 Report Export",
         title="Report export",
         story="As management, I want to export reports so that I can share them.",
         ac=["CSV and PDF export"]),
]
