"""Render docs/product/backlog.md from scripts/backlog.py (the initial product backlog snapshot)."""

from collections import defaultdict
from pathlib import Path

from backlog import BACKLOG, EPICS, SPRINT_GOALS, sprint_dates

OUT = Path(__file__).resolve().parent.parent / "docs" / "product" / "backlog.md"


def main():
    by_sprint = defaultdict(list)
    for item in BACKLOG:
        by_sprint[item["sprint"]].append(item)

    total = sum(i["points"] for i in BACKLOG if i["sprint"])
    stretch = sum(i["points"] for i in BACKLOG if not i["sprint"])
    lines = [
        "# Initial Product Backlog",
        "",
        "> Snapshot generated by `scripts/render_backlog_doc.py`. The **live** backlog is the GitHub Project board;",
        "> estimates and sprint assignments change at every sprint planning.",
        "",
        f"**Committed MVP scope:** {total} points across {len(SPRINT_GOALS)} one-week sprints "
        f"(≈ {total // len(SPRINT_GOALS)} points/sprint needed).  ",
        f"**Secondary / stretch scope:** {stretch} points (scheduled only if velocity allows).",
        "",
        "## Epics",
        "",
        "| Code | Epic | Items | Points |",
        "|---|---|---|---|",
    ]
    for code, (name, _) in EPICS.items():
        items = [i for i in BACKLOG if i["epic"] == code]
        lines.append(f"| {code} | {name} | {len(items)} | {sum(i['points'] for i in items)} |")

    for sprint in [*range(1, len(SPRINT_GOALS) + 1), None]:
        items = by_sprint[sprint]
        if sprint:
            start, end = sprint_dates(sprint)
            lines += ["", f"## Sprint {sprint}: {start:%a %d %b} – {end:%a %d %b %Y}", "",
                      f"**Goal:** {SPRINT_GOALS[sprint - 1]}  ", f"**Planned points:** {sum(i['points'] for i in items)}"]
        else:
            lines += ["", "## Unscheduled: secondary / stretch scope", ""]
        lines += ["", "| Type | Title | WBS | Epic | Priority | Pts |", "|---|---|---|---|---|---|"]
        for i in items:
            lines.append(f"| {i['type']} | {i['title']} | {i['wbs']} | {i['epic']} | {i['priority']} | {i['points']} |")

    lines += ["", "## Acceptance criteria", "",
              "Every item's acceptance criteria live in its GitHub issue body."]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
