# Generated by Django 6.0.9 on 2026-10-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable id used by the frontend.', unique=True)),
                ('name', models.CharField(help_text='Generic name.', max_length=150)),
                ('strength', models.CharField(max_length=60)),
                ('form', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('unit', models.CharField(help_text='Counting unit, e.g. "tablets", "vials".', max_length=30)),
                ('reorder_level', models.PositiveIntegerField()),
                ('daily_use', models.DecimalField(decimal_places=1, help_text='Average units used per day over the last 30 days.', max_digits=8)),
                ('location', models.CharField(max_length=100)),
                ('high_alert', models.BooleanField(default=False, help_text='On the ISMP list of high-alert medications.')),
                ('controlled', models.BooleanField(default=False, help_text='Controlled drug: kept in the CD cabinet.')),
            ],
            options={
                'ordering': ['name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('expires_on', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['expires_on'],
                'constraints': [models.UniqueConstraint(fields=('medicine', 'number'), name='pharmacy_batch_unique_per_medicine')],
            },
        ),
    ]
