# Generated by Django 6.0.9 on 2026-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepting', 'Accepting patients'), ('busy', 'Very busy'), ('diverting', 'Not accepting ambulances')], default='accepting', max_length=20)),
                ('wait_minutes', models.PositiveIntegerField(default=0)),
                ('waiting_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'emergency status',
            },
        ),
    ]
